version: "3.1"
services:
  www:
    build:
      context: .  
      dockerfile: ./nginx/Dockerfile  
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    networks:
      - default
  php:
    image: php:8.0-fpm
    volumes:
      - ./www:/var/www/html
    networks:
      - default
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: test_db  
      MYSQL_USER: user
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dump:/docker-entrypoint-initdb.d  
      - persistent:/var/lib/mysql
    networks:
      - default  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: test
    networks:
      - default  

volumes:
  persistent:
networks:
  default:
