global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus_service'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nodejs_service'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Cambiar a 'host.docker.internal' si estás en Windows/Mac
