version: '3.8'

services:
  tomcat:
    build:
      context: ./tomcat
    ports:
      - "8080:8080"
  
  mysql:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_db
    ports:
      - "3307:3306"

  phpmyadmin:
    build:
      context: ./phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
