# Version que se va a utilizar
version: '3.8'
# Servicios a utilizar
services:
# La bbdd debe ser Mysql para que funcione con PhpMyAdmin
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
    # Se hace referencia al servicio de BBDD
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
      # Puerto a utilizar
    ports:
      - "8080:80"
    networks:
      - backend_network

volumes:
  db_data:

networks:
  backend_network:
